# Generated by Django 5.0.6 on 2024-06-14 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzeria',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='email',
            field=models.EmailField(blank=True, max_length=245),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\1?\\d{9,10}')]),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='street',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='website',
            field=models.URLField(blank=True, max_length=420),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='zip_code',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
