# Generated by Django 5.0.7 on 2024-07-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
