# Generated by Django 5.0.7 on 2024-07-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_used', models.CharField(max_length=100)),
                ('bank_account_name', models.CharField(max_length=100)),
                ('date_of_transaction', models.DateField()),
                ('receipt', models.ImageField(upload_to='receipts/')),
            ],
        ),
    ]
