# Generated by Django 5.0.7 on 2024-07-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Church',
        ),
    ]
